export interface City {
  id: number; // Added a unique ID for the city relative to the list or global
  nameEn: string;
  nameAr: string;
}

export interface Governorate {
  id: number;
  nameEn: string;
  nameAr: string;
  cities: City[];
}

export const egyptianGovernorates: Governorate[] = [
  {
    id: 1,
    nameEn: "Cairo",
    nameAr: "القاهرة",
    cities: [
      { id: 1, nameEn: "Cairo", nameAr: "القاهرة" },
      { id: 2, nameEn: "New Cairo", nameAr: "القاهرة الجديدة" },
      { id: 3, nameEn: "Helwan", nameAr: "حلوان" },
      { id: 4, nameEn: "Nasr City", nameAr: "مدينة نصر" },
      { id: 5, nameEn: "Heliopolis", nameAr: "مصر الجديدة" },
      { id: 6, nameEn: "El Marg", nameAr: "المرج" },
      { id: 7, nameEn: "Maadi", nameAr: "المعادي" },
      { id: 8, nameEn: "Zamalek", nameAr: "الزمالك" },
      { id: 9, nameEn: "Badr City", nameAr: "مدينة بدر" },
      { id: 10, nameEn: "Shubra", nameAr: "شبرا" },
      { id: 11, nameEn: "Almaza", nameAr: "ألماظة" },
      { id: 12, nameEn: "Sheraton", nameAr: "شيراتون" },
      { id: 13, nameEn: "Ramses", nameAr: "رمسيس" },
      { id: 14, nameEn: "15th of May", nameAr: "15 مايو" },
    ],
  },
  {
    id: 2,
    nameEn: "Giza",
    nameAr: "الجيزة",
    cities: [
      { id: 15, nameEn: "Giza", nameAr: "الجيزة" },
      { id: 16, nameEn: "6th of October", nameAr: "السادس من أكتوبر" },
      { id: 17, nameEn: "Sheikh Zayed", nameAr: "الشيخ زايد" },
      { id: 18, nameEn: "Haram", nameAr: "الهرم" },
      { id: 19, nameEn: "Faisal", nameAr: "فيصل" },
      { id: 20, nameEn: "Imbaba", nameAr: "إمبابة" },
      { id: 21, nameEn: "Mohandessin", nameAr: "المهندسين" },
      { id: 22, nameEn: "Dokki", nameAr: "الدقي" },
      { id: 23, nameEn: "Al Ayyat", nameAr: "العياط" },
      { id: 24, nameEn: "Al Hawamdiya", nameAr: "الحوامدية" },
      { id: 25, nameEn: "Al Badrasheen", nameAr: "البدرشين" },
      { id: 26, nameEn: "Oseem", nameAr: "أوسيم" },
      { id: 27, nameEn: "Kerdasa", nameAr: "كرداسة" },
      { id: 28, nameEn: "Al Saf", nameAr: "الصف" },
      { id: 29, nameEn: "Al Waha", nameAr: "الواحات البحرية" }, // Al Bawiti
    ],
  },
  {
    id: 3,
    nameEn: "Alexandria",
    nameAr: "الإسكندرية",
    cities: [
      { id: 30, nameEn: "Alexandria", nameAr: "الإسكندرية" },
      { id: 31, nameEn: "Borg El Arab", nameAr: "برج العرب" },
      { id: 32, nameEn: "Agami", nameAr: "العجمي" },
      { id: 33, nameEn: "Smouha", nameAr: "سموحة" },
      { id: 34, nameEn: "Sidi Gaber", nameAr: "سيدي جابر" },
      { id: 35, nameEn: "Victoria", nameAr: "فيكتوريا" },
      { id: 36, nameEn: "Fleming", nameAr: "فلمنج" }, // Flaminj
    ],
  },
  {
    id: 4,
    nameEn: "Dakahlia",
    nameAr: "الدقهلية",
    cities: [
      { id: 37, nameEn: "Mansoura", nameAr: "المنصورة" },
      { id: 38, nameEn: "Talkha", nameAr: "طلخا" },
      { id: 39, nameEn: "Mit Ghamr", nameAr: "ميت غمر" },
      { id: 40, nameEn: "Dekernes", nameAr: "دكرنس" },
      { id: 41, nameEn: "Aga", nameAr: "أجا" },
      { id: 42, nameEn: "Menia El Nasr", nameAr: "منية النصر" },
      { id: 43, nameEn: "Sinbillawain", nameAr: "السنبلاوين" },
      { id: 44, nameEn: "El Kurdi", nameAr: "الكردي" },
      { id: 45, nameEn: "Bani Ubayd", nameAr: "بني عبيد" },
      { id: 46, nameEn: "Al Manzala", nameAr: "المنزلة" },
      { id: 47, nameEn: "Sherbin", nameAr: "شربين" },
      { id: 48, nameEn: "Belqas", nameAr: "بلقاس" },
      { id: 49, nameEn: "Nabaroh", nameAr: "نبروه" },
      { id: 50, nameEn: "Gamasa", nameAr: "جمصة" },
    ],
  },
  {
    id: 5,
    nameEn: "Red Sea",
    nameAr: "البحر الأحمر",
    cities: [
      { id: 51, nameEn: "Hurghada", nameAr: "الغردقة" },
      { id: 52, nameEn: "Ras Ghareb", nameAr: "رأس غارب" },
      { id: 53, nameEn: "Safaga", nameAr: "سفاجا" },
      { id: 54, nameEn: "El Qusiar", nameAr: "القصير" },
      { id: 55, nameEn: "Marsa Alam", nameAr: "مرسى علم" },
      { id: 56, nameEn: "El Gouna", nameAr: "الجونة" },
      { id: 57, nameEn: "Shalateen", nameAr: "شلاتين" },
      { id: 58, nameEn: "Halaib", nameAr: "حلايب" },
    ],
  },
  {
    id: 6,
    nameEn: "Beheira",
    nameAr: "البحيرة",
    cities: [
      { id: 59, nameEn: "Damanhour", nameAr: "دمنهور" },
      { id: 60, nameEn: "Kafr El Dawar", nameAr: "كفر الدوار" },
      { id: 61, nameEn: "Rashid", nameAr: "رشيد" },
      { id: 62, nameEn: "Edko", nameAr: "إدكو" },
      { id: 63, nameEn: "Abu El Matamir", nameAr: "أبو المطامير" },
      { id: 64, nameEn: "Abu Hommos", nameAr: "أبو حمص" },
      { id: 65, nameEn: "Delengat", nameAr: "الدلنجات" },
      { id: 66, nameEn: "Mahmoudiyah", nameAr: "المحمودية" },
      { id: 67, nameEn: "Rahmaniyah", nameAr: "الرحمانية" },
      { id: 68, nameEn: "Itay El Barud", nameAr: "إيتاي البارود" },
      { id: 69, nameEn: "Hosh Issa", nameAr: "حوش عيسى" },
      { id: 70, nameEn: "Kom Hamada", nameAr: "كوم حمادة" },
      { id: 71, nameEn: "Badr", nameAr: "بدر" },
      { id: 72, nameEn: "Wadi El Natrun", nameAr: "وادي النطرون" },
    ],
  },
  {
    id: 7,
    nameEn: "Fayoum",
    nameAr: "الفيوم",
    cities: [
      { id: 73, nameEn: "Fayoum", nameAr: "الفيوم" },
      { id: 74, nameEn: "Fayoum El Gedida", nameAr: "الفيوم الجديدة" },
      { id: 75, nameEn: "Tamiya", nameAr: "طامية" },
      { id: 76, nameEn: "Snores", nameAr: "سنورس" },
      { id: 77, nameEn: "Etsa", nameAr: "إطسا" },
      { id: 78, nameEn: "Ibshway", nameAr: "إبشواي" },
      { id: 79, nameEn: "Yusuf El Sediaq", nameAr: "يوسف الصديق" },
    ],
  },
  {
    id: 8,
    nameEn: "Gharbia",
    nameAr: "الغربية",
    cities: [
      { id: 80, nameEn: "Tanta", nameAr: "طنطا" },
      { id: 81, nameEn: "Al Mahalla Al Kobra", nameAr: "المحلة الكبرى" },
      { id: 82, nameEn: "Kafr El Zayat", nameAr: "كفر الزيات" },
      { id: 83, nameEn: "Zefta", nameAr: "زفتى" },
      { id: 84, nameEn: "El Santa", nameAr: "السنطة" },
      { id: 85, nameEn: "Qutour", nameAr: "قطور" },
      { id: 86, nameEn: "Basyoun", nameAr: "بسيون" },
      { id: 87, nameEn: "Samannoud", nameAr: "سمنود" },
    ],
  },
  {
    id: 9,
    nameEn: "Ismailia",
    nameAr: "الإسماعيلية",
    cities: [
      { id: 88, nameEn: "Ismailia", nameAr: "الإسماعيلية" },
      { id: 89, nameEn: "Fayed", nameAr: "فايد" },
      { id: 90, nameEn: "Qantara Sharq", nameAr: "القنطرة شرق" },
      { id: 91, nameEn: "Qantara Gharb", nameAr: "القنطرة غرب" },
      { id: 92, nameEn: "El Tal El Kebir", nameAr: "التا الكبير" },
      { id: 93, nameEn: "Abu Sawir", nameAr: "أبو صوير" },
      { id: 94, nameEn: "Qassassin", nameAr: "القصاصين" },
    ],
  },
  {
    id: 10,
    nameEn: "Monufia",
    nameAr: "المنوفية",
    cities: [
      { id: 95, nameEn: "Shibin El Kom", nameAr: "شبين الكوم" },
      { id: 96, nameEn: "Menouf", nameAr: "منوف" },
      { id: 97, nameEn: "Ashmoun", nameAr: "أشمون" },
      { id: 98, nameEn: "Sers El Lyan", nameAr: "سرس الليان" },
      { id: 99, nameEn: "Tala", nameAr: "تلا" },
      { id: 100, nameEn: "El Bagour", nameAr: "الباجور" },
      { id: 101, nameEn: "El Shohada", nameAr: "الشهداء" },
      { id: 102, nameEn: "Sadat City", nameAr: "مدينة السادات" },
      { id: 103, nameEn: "Quweisna", nameAr: "قويسنا" },
      { id: 104, nameEn: "Berkat El Saba", nameAr: "بركة السبع" },
    ],
  },
  {
    id: 11,
    nameEn: "Minya",
    nameAr: "المنيا",
    cities: [
      { id: 105, nameEn: "Minya", nameAr: "المنيا" },
      { id: 106, nameEn: "Minya El Gedida", nameAr: "المنيا الجديدة" },
      { id: 107, nameEn: "El Adwa", nameAr: "العدوة" },
      { id: 108, nameEn: "Maghagha", nameAr: "مغاغة" },
      { id: 109, nameEn: "Bani Mazar", nameAr: "بني مزار" },
      { id: 110, nameEn: "Matay", nameAr: "مطاي" },
      { id: 111, nameEn: "Samalut", nameAr: "سمالوط" },
      { id: 112, nameEn: "Madinat El Fekria", nameAr: "مدينة الفكرية" },
      { id: 113, nameEn: "Melawy", nameAr: "ملوي" },
      { id: 114, nameEn: "Deir Mawas", nameAr: "دير مواس" },
    ],
  },
  {
    id: 12,
    nameEn: "Qalyubia",
    nameAr: "القليوبية",
    cities: [
      { id: 115, nameEn: "Banha", nameAr: "بنها" },
      { id: 116, nameEn: "Qalyub", nameAr: "قليوب" },
      { id: 117, nameEn: "Shubra Al Khaimah", nameAr: "شبرا الخيمة" },
      { id: 118, nameEn: "Al Qanater Charity", nameAr: "القناطر الخيرية" },
      { id: 119, nameEn: "Khanka", nameAr: "الخانكة" },
      { id: 120, nameEn: "Kafr Shukr", nameAr: "كفر شكر" },
      { id: 121, nameEn: "Tukh", nameAr: "طوخ" },
      { id: 122, nameEn: "Qaha", nameAr: "قها" },
      { id: 123, nameEn: "Obour", nameAr: "العبور" },
      { id: 124, nameEn: "Khusus", nameAr: "الخصوص" },
    ],
  },
  {
    id: 13,
    nameEn: "New Valley",
    nameAr: "الوادي الجديد",
    cities: [
      { id: 125, nameEn: "El Kharga", nameAr: "الخارجة" },
      { id: 126, nameEn: "Paris", nameAr: "باريس" },
      { id: 127, nameEn: "Mout", nameAr: "موط" },
      { id: 128, nameEn: "Farafra", nameAr: "الفرافرة" },
      { id: 129, nameEn: "Balat", nameAr: "بلاط" },
    ],
  },
  {
    id: 14,
    nameEn: "Suez",
    nameAr: "السويس",
    cities: [
      { id: 130, nameEn: "Suez", nameAr: "السويس" },
      { id: 131, nameEn: "Arbaeen", nameAr: "الأربعين" },
      { id: 132, nameEn: "Ganayen", nameAr: "الجناين" },
      { id: 133, nameEn: "Faysal", nameAr: "فيصل" },
      { id: 134, nameEn: "Attaka", nameAr: "عتاقة" },
      { id: 135, nameEn: "Ain Sokhna", nameAr: "العين السخنة" },
    ],
  },
  {
    id: 15,
    nameEn: "Aswan",
    nameAr: "أسوان",
    cities: [
      { id: 136, nameEn: "Aswan", nameAr: "أسوان" },
      { id: 137, nameEn: "Aswan El Gedida", nameAr: "أسوان الجديدة" },
      { id: 138, nameEn: "Drau", nameAr: "دراو" },
      { id: 139, nameEn: "Kom Ombo", nameAr: "كوم أمبو" },
      { id: 140, nameEn: "Nasr Al Nuba", nameAr: "نصر النوبة" },
      { id: 141, nameEn: "Kalabsha", nameAr: "كلابشة" },
      { id: 142, nameEn: "Edfu", nameAr: "إدفو" },
      { id: 143, nameEn: "Al-Radisiyah", nameAr: "الرديسية" },
      { id: 144, nameEn: "Al Basilia", nameAr: "البصيلية" },
      { id: 145, nameEn: "Al Sibaeia", nameAr: "السباعية" },
      { id: 146, nameEn: "Abu Simbel", nameAr: "أبو سمبل" },
    ],
  },
  {
    id: 16,
    nameEn: "Assiut",
    nameAr: "أسيوط",
    cities: [
      { id: 147, nameEn: "Assiut", nameAr: "أسيوط" },
      { id: 148, nameEn: "Assiut El Gedida", nameAr: "أسيوط الجديدة" },
      { id: 149, nameEn: "Dayrout", nameAr: "ديروط" },
      { id: 150, nameEn: "Manfalut", nameAr: "منفلوط" },
      { id: 151, nameEn: "Qusiya", nameAr: "القوصية" },
      { id: 152, nameEn: "Abnoub", nameAr: "أبنوب" },
      { id: 153, nameEn: "Abu Tig", nameAr: "أبو تيج" },
      { id: 154, nameEn: "El Ghanaim", nameAr: "الغنايم" },
      { id: 155, nameEn: "Sahel Selim", nameAr: "ساحل سليم" },
      { id: 156, nameEn: "El Badari", nameAr: "البداري" },
      { id: 157, nameEn: "Sidfa", nameAr: "صدفا" },
    ],
  },
  {
    id: 17,
    nameEn: "Beni Suef",
    nameAr: "بني سويف",
    cities: [
      { id: 158, nameEn: "Beni Suef", nameAr: "بني سويف" },
      { id: 159, nameEn: "Beni Suef El Gedida", nameAr: "بني سويف الجديدة" },
      { id: 160, nameEn: "Al Wasta", nameAr: "الواسطى" },
      { id: 161, nameEn: "Nasser", nameAr: "ناصر" },
      { id: 162, nameEn: "Ehnasia", nameAr: "إهناسيا" },
      { id: 163, nameEn: "Biba", nameAr: "ببا" },
      { id: 164, nameEn: "Fashn", nameAr: "الفشن" },
      { id: 165, nameEn: "Somasta", nameAr: "سمسطا" },
    ],
  },
  {
    id: 18,
    nameEn: "Port Said",
    nameAr: "بورسعيد",
    cities: [
      { id: 166, nameEn: "Port Said", nameAr: "بورسعيد" },
      { id: 167, nameEn: "Port Fouad", nameAr: "بورفؤاد" },
      { id: 168, nameEn: "El Arab", nameAr: "العرب" },
      { id: 169, nameEn: "El Zohur", nameAr: "الزهور" },
      { id: 170, nameEn: "El Sharq", nameAr: "الشرق" },
      { id: 171, nameEn: "El Dawahi", nameAr: "الضواحي" },
      { id: 172, nameEn: "El Manakh", nameAr: "المناخ" },
      { id: 173, nameEn: "Mubarak", nameAr: "مبارك" },
    ],
  },
  {
    id: 19,
    nameEn: "Damietta",
    nameAr: "دمياط",
    cities: [
      { id: 174, nameEn: "Damietta", nameAr: "دمياط" },
      { id: 175, nameEn: "New Damietta", nameAr: "دمياط الجديدة" },
      { id: 176, nameEn: "Ras El Bar", nameAr: "رأس البر" },
      { id: 177, nameEn: "Faraskour", nameAr: "فارسكور" },
      { id: 178, nameEn: "Zarqa", nameAr: "الزرقا" },
      { id: 179, nameEn: "Kafr Saad", nameAr: "كفر سعد" },
      { id: 180, nameEn: "El-Roda", nameAr: "الروضة" },
      { id: 181, nameEn: "El Sarw", nameAr: "السرو" },
      { id: 182, nameEn: "Ezbet El Burg", nameAr: "عزبة البرج" },
      { id: 183, nameEn: "Mit Abu Ghaleb", nameAr: "ميت أبو غالب" },
    ],
  },
  {
    id: 20,
    nameEn: "Sharkia",
    nameAr: "الشرقية",
    cities: [
      { id: 184, nameEn: "Zagazig", nameAr: "الزقازيق" },
      { id: 185, nameEn: "Al Ashr Men Ramadan", nameAr: "العاشر من رمضان" },
      { id: 186, nameEn: "Minya Al Qamh", nameAr: "منيا القمح" },
      { id: 187, nameEn: "Belbeis", nameAr: "بلبيس" },
      { id: 188, nameEn: "Mashtoul El Souq", nameAr: "مشتول السوق" },
      { id: 189, nameEn: "Qenaiat", nameAr: "القنايات" },
      { id: 190, nameEn: "Abu Hammad", nameAr: "أبو حماد" },
      { id: 191, nameEn: "El Qurain", nameAr: "القرين" },
      { id: 192, nameEn: "Hehia", nameAr: "ههيا" },
      { id: 193, nameEn: "Abu Kabir", nameAr: "أبو كبير" },
      { id: 194, nameEn: "Facus", nameAr: "فاقوس" },
      { id: 195, nameEn: "El Salihia El Gedida", nameAr: "الصالحية الجديدة" },
      { id: 196, nameEn: "Al Ibrahimiyah", nameAr: "الإبراهيمية" },
      { id: 197, nameEn: "Deirb Negm", nameAr: "ديرب نجم" },
      { id: 198, nameEn: "Kafr Saqr", nameAr: "كفر صقر" },
      { id: 199, nameEn: "Awlad Saqr", nameAr: "أولاد صقر" },
      { id: 200, nameEn: "Husseiniya", nameAr: "الحسينية" },
      { id: 201, nameEn: "San El Hagar", nameAr: "صان الحجر القبلية" },
      { id: 202, nameEn: "Awlad Saqr", nameAr: "منشأة أبو عمر" },
    ],
  },
  {
    id: 21,
    nameEn: "South Sinai",
    nameAr: "جنوب سيناء",
    cities: [
      { id: 203, nameEn: "Tor Sinai", nameAr: "طور سيناء" },
      { id: 204, nameEn: "Sharm El Sheikh", nameAr: "شرم الشيخ" },
      { id: 205, nameEn: "Dahab", nameAr: "دهب" },
      { id: 206, nameEn: "Nuweiba", nameAr: "نويبع" },
      { id: 207, nameEn: "Taba", nameAr: "طابا" },
      { id: 208, nameEn: "Saint Catherine", nameAr: "سانت كاترين" },
      { id: 209, nameEn: "Abu Redis", nameAr: "أبو رديس" },
      { id: 210, nameEn: "Abu Zenima", nameAr: "أبو زنيمة" },
      { id: 211, nameEn: "Ras Sidr", nameAr: "رأس سدر" },
    ],
  },
  {
    id: 22,
    nameEn: "Kafr El Sheikh",
    nameAr: "كفر الشيخ",
    cities: [
      { id: 212, nameEn: "Kafr El Sheikh", nameAr: "كفر الشيخ" },
      { id: 213, nameEn: "Desouq", nameAr: "دسوق" },
      { id: 214, nameEn: "Sidi Salem", nameAr: "سيدي سالم" },
      { id: 215, nameEn: "Metoubes", nameAr: "مطوبس" },
      { id: 216, nameEn: "Fouwah", nameAr: "فوة" },
      { id: 217, nameEn: "Baltim", nameAr: "بلطيم" },
      { id: 218, nameEn: "Masief Baltim", nameAr: "مصيف بلطيم" },
      { id: 219, nameEn: "Hamoul", nameAr: "الحامول" },
      { id: 220, nameEn: "Biyala", nameAr: "بيلا" },
      { id: 221, nameEn: "Riyadh", nameAr: "الرياض" },
      { id: 222, nameEn: "Qalin", nameAr: "قلين" },
      { id: 223, nameEn: "Burullus", nameAr: "البرلس" },
    ],
  },
  {
    id: 23,
    nameEn: "Matrouh",
    nameAr: "مطروح",
    cities: [
      { id: 224, nameEn: "Marsa Matrouh", nameAr: "مرسى مطروح" },
      { id: 225, nameEn: "El Hamam", nameAr: "الحمام" },
      { id: 226, nameEn: "Alamein", nameAr: "العلمين" },
      { id: 227, nameEn: "Dabaa", nameAr: "الضبعة" },
      { id: 228, nameEn: "Al-Nagila", nameAr: "النجيلة" },
      { id: 229, nameEn: "Sidi Brani", nameAr: "سيدي براني" },
      { id: 230, nameEn: "Salloum", nameAr: "السلوم" },
      { id: 231, nameEn: "Siwa", nameAr: "سيوة" },
    ],
  },
  {
    id: 24,
    nameEn: "Luxor",
    nameAr: "الأقصر",
    cities: [
      { id: 232, nameEn: "Luxor", nameAr: "الأقصر" },
      { id: 233, nameEn: "New Luxor", nameAr: "الأقصر الجديدة" },
      { id: 234, nameEn: "Esna", nameAr: "إسنا" },
      { id: 235, nameEn: "New Tiba", nameAr: "طيبة الجديدة" },
      { id: 236, nameEn: "Al Zinia", nameAr: "الزينية" },
      { id: 237, nameEn: "Al Bayadieh", nameAr: "البياضية" },
      { id: 238, nameEn: "Al Qarna", nameAr: "القرنة" },
      { id: 239, nameEn: "Armant", nameAr: "أرمنت" },
      { id: 240, nameEn: "Al Tod", nameAr: "الطود" },
    ],
  },
  {
    id: 25,
    nameEn: "Qena",
    nameAr: "قنا",
    cities: [
      { id: 241, nameEn: "Qena", nameAr: "قنا" },
      { id: 242, nameEn: "New Qena", nameAr: "قنا الجديدة" },
      { id: 243, nameEn: "Abu Tesht", nameAr: "أبو تشت" },
      { id: 244, nameEn: "Nag Hammadi", nameAr: "نجع حمادي" },
      { id: 245, nameEn: "Deshna", nameAr: "دشنا" },
      { id: 246, nameEn: "Al Waqf", nameAr: "الوقف" },
      { id: 247, nameEn: "Qift", nameAr: "قفط" },
      { id: 248, nameEn: "Qus", nameAr: "قوص" },
      { id: 249, nameEn: "Farshout", nameAr: "فرشوط" },
      { id: 250, nameEn: "Naqada", nameAr: "نقادة" },
    ],
  },
  {
    id: 26,
    nameEn: "North Sinai",
    nameAr: "شمال سيناء",
    cities: [
      { id: 251, nameEn: "Arish", nameAr: "العريش" },
      { id: 252, nameEn: "Sheikh Zuweid", nameAr: "الشيخ زويد" },
      { id: 253, nameEn: "Nakhl", nameAr: "نخل" },
      { id: 254, nameEn: "Rafah", nameAr: "رفح" },
      { id: 255, nameEn: "Bir al-Abed", nameAr: "بئر العبد" },
      { id: 256, nameEn: "Al Hasana", nameAr: "الحسنة" },
    ],
  },
  {
    id: 27,
    nameEn: "Sohag",
    nameAr: "سوهاج",
    cities: [
      { id: 257, nameEn: "Sohag", nameAr: "سوهاج" },
      { id: 258, nameEn: "Sohag El Gedida", nameAr: "سوهاج الجديدة" },
      { id: 259, nameEn: "Akhmim", nameAr: "أخميم" },
      { id: 260, nameEn: "Akhmim El Gedida", nameAr: "أخميم الجديدة" },
      { id: 261, nameEn: "Al Balyana", nameAr: "البلينا" },
      { id: 262, nameEn: "Al Maragha", nameAr: "المراغة" },
      { id: 263, nameEn: "Al Munsha'a", nameAr: "المنشأة" },
      { id: 264, nameEn: "Dar El Salam", nameAr: "دار السلام" },
      { id: 265, nameEn: "Gerga", nameAr: "جرجا" },
      { id: 266, nameEn: "Juhayna", nameAr: "جهينة" },
      { id: 267, nameEn: "Saqulta", nameAr: "ساقلتة" },
      { id: 268, nameEn: "Tama", nameAr: "طما" },
      { id: 269, nameEn: "Tahta", nameAr: "طهطا" },
      { id: 270, nameEn: "Al Kawthar", nameAr: "الكوثر" },
    ],
  },
];

export const getCitiesByGovernorate = (governorateId: number): City[] => {
  const governorate = egyptianGovernorates.find((g) => g.id === governorateId);
  return governorate?.cities || [];
};